### ISSUE TITLE
Add support for aarch64-unknown-linux-gnu

### ISSUE THREAD

**Issue by Mogost** [urschrei/rdp#16]
Hi there, I am a user of the RDP library and I would like to request support for the aarch64-unknown-linux-gnu architecture.

Currently, the library supports a variety of architectures, but aarch64-unknown-linux-gnu is not one of them. I believe this support will greatly benefit the community, especially as more developers are adopting aarch64-unknown-linux-gnu architecture.

Could you please consider adding support for aarch64-unknown-linux-gnu?

Thank you for your time and consideration.

**Comment by urschrei** [comment]
I don't have a use case for aarch64-unknown-linux-gnu at the moment, and building on the platform isn't straightforward. I'm happy to accept a PR, but I don't have time to figure it out myself at the moment.
