### ISSUE TITLE
bug in examples/example.c ?

### ISSUE THREAD

**Issue by FiveLeavesLeft** [urschrei/rdp#23]
Is the "len" field in external array the number of coordinates in data or the size of the data in bytes?

I ask because it seems inconsistent in example.c:

> size_t len = sizeof(input);
> externalarray ea = {
>     .len = len,
>     .data = vp
>   };
> 

len is 80, the number of bytes in input

But on the result you do the loop:

> // print all values in a loop
>   for (int i = 0; i < adj.len; i++)
>       printf("%f\n", ((double*)adj.data)[i]);

Which implies the len field is the number of coordinates.

Thanks.

**Comment by urschrei** [comment]
I don't write enough c to know, sorry!
